### PR TITLE
Build arch

### PR DESCRIPTION
**Pull request by noonon**
Can I change architecture of the build's files. For example, add all html files in some directory?
Can I change html result in the build to jade templates?

### CODE REVIEW

**Comment by artem-malko** [comment]
@noonon first of all, it is very strange, that you want to merge my own commits)
1) Yes, it is possible. You can create any type of File Structure in markup/pages and it will be saved in build.
2) That do you mean?

**Comment by noonon** [comment]
I am sorry, it my first pull request on github.
i mean, that if i need jade files in production for dynamic generate html.
I understand correctly, that tars is a workflow for front generation and result of his work is /build/?!

**Comment by artem-malko** [comment]
It is really simple to implement. You can init TARS with jade as templater. Then you need to copy compile-templates.js to user-tasks directory. It is needed to not modify TARS-tasks.
In that file (compile-templates.js) you need to rename task name and fix jade execution:
```javascript
jade({ pretty: true, locals: concatModulesData() })
// You need to replace it with
jade({ pretty: true, locals: concatModulesData(), client: true })
```

After all, you need to go to gulpfile.js and change html:compile-templates task to yours.

**Comment by artem-malko** [comment]
Yes, you understood it correctly)

**Comment by noonon** [comment]
Thank for recommendations. :3

**Comment by artem-malko** [comment]
@noonon So, can I close this request?

**Comment by noonon** [comment]
Yeap

**Comment by artem-malko** [comment]
@noonon please, if you have just question, make an issue, not pull request)

**Comment by noonon** [comment]
Okay.

**Pull request closed without merging**
