### PR TITLE
Issue 279 move all tars repos to tars

### LINKED ISSUE #279: Move all tars-* reps to tars
It is quite hard to maintain so many repositories: tars-jade, tars-scss and so on. So, I've decided to merge it into main tars rep.

### PR DESCRIPTION
**Pull request by ilyoff**
resolves #279 . All tars-* repos are moved now to local "templates" folder, which is removing after tars init.

### CODE REVIEW

**Comment by artem-malko** [comment]
Thank you a lot)

Will review during next 2-3 days.

**Comment by artem-malko** [comment]
Great!
Everything is ok with code) I will test it locally today evening.

**Comment by artem-malko** [comment]
Only one fix is needed! Need to bump version of tars in tars.json and package.json to 1.11.0

**Comment by ilyoff** [comment]
@artem-malko done

**Comment by artem-malko** [comment]
Everything is ok. I'm going to merge it. 
Thank you a lot!)

**Pull request merged**
